import * as H from './helpers.js';

console.log('_____CREATE CHARACTER_____');
console.log(' ');
console.log('Character Name Options: ', H.randomCharacterNames());
console.log('Body Type: ', H.twoOptions('A', 'B'));
console.log('Age: See Detailed Appearance Section');
console.log('Origin: ', Math.round(Math.random() * 10));
console.log('Keepsake: ', Math.round(Math.random() * 9));
console.log(' ');
console.log('_____DETAILED APPEARANCE_____');
console.log(' ');
console.log('Age: ', H.ageSelector());
console.log('Voice: ', H.voiceSelector());
console.log('Alter Skin Color: ', H.colorSelector());
console.log(' ');
console.log('_____ALTER FACE & HAIR_____');
console.log(' ');
console.log('_____ADJUST FACE TEMPLATE_____');
console.log(' ');
console.log('Bone Structure: ', Math.ceil(Math.random() * 6));
console.log('Form Emphasis: ', Math.ceil(Math.random() * 255));
console.log('Apparent Age: ', Math.ceil(Math.random() * 255));
console.log('Facial Aesthetic: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____FACE STRUCTURE_____');
console.log(' ');
console.log('_____FACIAL BALANCE_____');
console.log(' ');
console.log('Nose Size: ', Math.ceil(Math.random() * 255));
console.log('Nose/Forehead Ratio: ', Math.ceil(Math.random() * 255));
console.log('Face Protrusion: ', Math.ceil(Math.random() * 255));
console.log('Vert. Face Ratio: ', Math.ceil(Math.random() * 255));
console.log('Facial Feature Slant: ', Math.ceil(Math.random() * 255));
console.log('Horiz. Face Ratio: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____FOREHEAD/GLABELLA_____');
console.log(' ');
console.log('Forehead Depth: ', Math.ceil(Math.random() * 255));
console.log('Forehead Protrusion: ', Math.ceil(Math.random() * 255));
console.log('Nose Bridge Height: ', Math.ceil(Math.random() * 255));
console.log('Bridge Protrusion 1: ', Math.ceil(Math.random() * 255));
console.log('Bridge Protrusion 2: ', Math.ceil(Math.random() * 255));
console.log('Nose Bridge Width: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____BROW RIDGE_____');
console.log(' ');
console.log('Brow Ridge Height: ', Math.ceil(Math.random() * 255));
console.log('Inner Brow Ridge: ', Math.ceil(Math.random() * 255));
console.log('Outer Brow Ridge: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____EYES_____');
console.log(' ');
console.log('Eye Position: ', Math.ceil(Math.random() * 255));
console.log('Eye Size: ', Math.ceil(Math.random() * 255));
console.log('Eye Slant: ', Math.ceil(Math.random() * 255));
console.log('Eye Spacing: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____NOSE RIDGE_____');
console.log(' ');
console.log('Nose Ridge Depth: ', Math.ceil(Math.random() * 255));
console.log('Nose Ridge Length: ', Math.ceil(Math.random() * 255));
console.log('Nose Position: ', Math.ceil(Math.random() * 255));
console.log('Nose Tip Height: ', Math.ceil(Math.random() * 255));
console.log('Nose Protrusion: ', Math.ceil(Math.random() * 255));
console.log('Nose Height: ', Math.ceil(Math.random() * 255));
console.log('Nose Slant: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____NOSTRILS_____');
console.log(' ');
console.log('Nostril Slant: ', Math.ceil(Math.random() * 255));
console.log('Nostril Size: ', Math.ceil(Math.random() * 255));
console.log('Nostril Width: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____CHEEKS_____');
console.log(' ');
console.log('Cheekbone Height: ', Math.ceil(Math.random() * 255));
console.log('Cheekbone Depth: ', Math.ceil(Math.random() * 255));
console.log('Cheekbone Width: ', Math.ceil(Math.random() * 255));
console.log('Cheekbone Protrusion: ', Math.ceil(Math.random() * 255));
console.log('Cheeks: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____LIPS_____');
console.log(' ');
console.log('Lip Shape: ', Math.ceil(Math.random() * 255));
console.log('Mouth Expression: ', Math.ceil(Math.random() * 255));
console.log('Lip Fullness: ', Math.ceil(Math.random() * 255));
console.log('Lip Size: ', Math.ceil(Math.random() * 255));
console.log('Lip Protrusion: ', Math.ceil(Math.random() * 255));
console.log('Lip Thickness: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____MOUTH_____');
console.log(' ');
console.log('Mouth Protrusion: ', Math.ceil(Math.random() * 255));
console.log('Mouth Slant: ', Math.ceil(Math.random() * 255));
console.log('Occlusion: ', Math.ceil(Math.random() * 255));
console.log('Mouth Position: ', Math.ceil(Math.random() * 255));
console.log('Mouth Width: ', Math.ceil(Math.random() * 255));
console.log('Mouth-Chin Distance: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____CHIN_____');
console.log(' ');
console.log('Chin Tip Position: ', Math.ceil(Math.random() * 255));
console.log('Chin Length: ', Math.ceil(Math.random() * 255));
console.log('Chin Protrusion: ', Math.ceil(Math.random() * 255));
console.log('Chin Depth: ', Math.ceil(Math.random() * 255));
console.log('Chin Size: ', Math.ceil(Math.random() * 255));
console.log('Chin Height: ', Math.ceil(Math.random() * 255));
console.log('Chin Width: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____JAW_____');
console.log(' ');
console.log('Jaw Protrusion: ', Math.ceil(Math.random() * 255));
console.log('Jaw Width: ', Math.ceil(Math.random() * 255));
console.log('Lower Jaw: ', Math.ceil(Math.random() * 255));
console.log('Jaw Contour: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____HAIR_____');
console.log(' ');
console.log('Hair: ', Math.ceil(Math.random() * 32));
console.log('Hair Color: ', H.colorSelector());
console.log('Luster: ', Math.ceil(Math.random() * 255));
console.log('Root Darkness: ', Math.ceil(Math.random() * 255));
console.log('White Hairs: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____EYEBROWS_____');
console.log(' ');
console.log('Brow: ', Math.ceil(Math.random() * 17));
console.log('Brow Color: ', H.colorSelector());
console.log('Luster: ', Math.ceil(Math.random() * 255));
console.log('Root Darkness: ', Math.ceil(Math.random() * 255));
console.log('White Hairs: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____FACIAL HAIR_____');
console.log(' ');
console.log(
  'Beard: | ',
  'Body Type B: ',
  Math.ceil(Math.random() * 17),
  'Body Type A: ',
  Math.ceil(Math.random() * 12)
);
console.log('Beard Color: ', H.colorSelector());
console.log('Luster: ', Math.ceil(Math.random() * 255));
console.log('Root Darkness: ', Math.ceil(Math.random() * 255));
console.log('White Hairs: ', Math.ceil(Math.random() * 255));
console.log('Stubble: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____EYELASHES_____');
console.log(' ');
console.log('Eyelashes: ', Math.ceil(Math.random() * 4));
console.log('Eyelash Color: ', H.colorSelector());
console.log(' ');
console.log('_____EYES_____');
console.log(' ');
console.log('Right Iris Size: ', Math.ceil(Math.random() * 255));
console.log('Right Iris Color: ', H.colorSelector());
console.log('Right Eye Clouding: ', Math.ceil(Math.random() * 255));
console.log('Right Clouding Color: ', H.colorSelector());
console.log('Right Eye White Color: ', H.colorSelector());
console.log('Right Eye Position: ', Math.ceil(Math.random() * 255));
console.log('Left Iris Size: ', Math.ceil(Math.random() * 255));
console.log('Left Iris Color: ', H.colorSelector());
console.log('Left Eye Clouding: ', Math.ceil(Math.random() * 255));
console.log('Left Clouding Color: ', H.colorSelector());
console.log('Left Eye White Color: ', H.colorSelector());
console.log('Left Eye Position: ', Math.ceil(Math.random() * 255));
console.log(' ');
console.log('_____SKIN FEATURES_____');
console.log(' ');
console.log('Pores: ', Math.ceil(Math.random() * 255));
console.log('Skin Luster: ', Math.ceil(Math.random() * 255));
console.log('Dark Circles: ', Math.ceil(Math.random() * 255));
console.log('Dark Circle Color: ', H.colorSelector());
console.log(' ');
console.log('_____COSMETICS_____');
console.log(' ');
console.log('Eyeliner: ', Math.ceil(Math.random() * 255));
console.log('Eyeliner Color: ', H.colorSelector());
console.log('Eyeshadow (Upper): ', Math.ceil(Math.random() * 255));
console.log('Eyeshadow Color (Upper): ', H.colorSelector());
console.log('Eyeshadow (Lower): ', Math.ceil(Math.random() * 255));
console.log('Eyeshadow Color (Lower): ', H.colorSelector());
console.log('Cheeks: ', Math.ceil(Math.random() * 255));
console.log('Cheek Color: ', H.colorSelector());
console.log('Lipstick: ', Math.ceil(Math.random() * 255));
console.log('Lipstick Color: ', H.colorSelector());
console.log(' ');
console.log('_____TATTOO/MARK/EYEPATCH_____');
console.log(' ');
console.log('Tattoo/Mark: ', Math.ceil(Math.random() * 38));
console.log('Tattoo/Mark Color: ', H.colorSelector());
console.log(' ');
console.log('--> TWEAK TATTOO/MARK -->');
console.log(' ');
console.log('Position (Vert.): ', Math.ceil(Math.random() * 255));
console.log('Position (Horiz.): ', Math.ceil(Math.random() * 255));
console.log('Angle: ', Math.ceil(Math.random() * 255));
console.log('Expansion: ', Math.ceil(Math.random() * 255));
console.log('Flip: ', H.twoOptions('On', 'Off'));
console.log(' ');
console.log('<-- <--');
console.log(' ');
console.log('Eyepatch: ', Math.ceil(Math.random() * 4));
console.log('Eyepatch Color: ', H.colorSelector());
console.log(' ');
console.log('_____ALTER BODY_____');
console.log(' ');
console.log('Head: ', Math.ceil(Math.random() * 255));
console.log('Chest: ', Math.ceil(Math.random() * 255));
console.log('Abdomen: ', Math.ceil(Math.random() * 255));
console.log('Arms: ', Math.ceil(Math.random() * 255));
console.log('Legs: ', Math.ceil(Math.random() * 255));
console.log('Body Hair: ', Math.ceil(Math.random() * 255));
console.log('Body Hair Color: ', H.colorSelector());
console.log('Musculature: ', H.twoOptions('Standard', 'Muscular'));
console.log(' ');
console.log(' ');
console.log(' ');
console.log('_____END_____');
